# syntax=docker/dockerfile:1
FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt ./backend/requirements.txt
WORKDIR  ./backend
RUN pip install -r ./requirements.txt
WORKDIR /code

# copy project
COPY .. /code/
COPY /backend/settings_production.py /code/backend/settings_local.py

EXPOSE 8000